gee:
  project_name: ee-kaloina4
  data_last_date: '2025-06-10'
  raw_data_location: ../data/raw/image_GEE/2025-06-11,2025-12-31/
firms_NASA:
  API_url: https://firms.modaps.eosdis.nasa.gov/api/country/csv/35ae49800327f79d4046cf4fd1f86349/MODIS_NRT/MDG/10/
  data_last_date: '2025-06-24'
  raw_data_location: ../data/raw/csv_NASA/modis/instrument_modis_2025/
  interim_data_location: ../data/interim/csv_NASA/modis/instrument_modis_2025/
